import 'dart:io';

import 'package:flutter/services.dart';

class DesktopEntryService {
  static const String _assetIconPath =
      'assets/images/filepeek.png';

  static const String _appName = 'File Peek';

  static const String _comment =
      'Inspect files and project structures';

  Future<bool> createDesktopEntry() async {
    if (Platform.isLinux) {
      return _createLinuxDesktopEntry();
    }

    if (Platform.isWindows) {
      return _createWindowsShortcut();
    }

    if (Platform.isMacOS) {
      return _createMacOSApplication();
    }

    return false;
  }

  // ---------------------------------------------------------------------------
  // LINUX
  // ---------------------------------------------------------------------------

  Future<bool> _createLinuxDesktopEntry() async {
    final home = Platform.environment['HOME'];

    if (home == null || home.isEmpty) {
      return false;
    }

    final applicationsDir = Directory(
      '$home/.local/share/applications',
    );

    final iconsDir = Directory(
      '$home/.local/share/icons/hicolor/256x256/apps',
    );

    try {
      await applicationsDir.create(recursive: true);
      await iconsDir.create(recursive: true);

      final iconFile = File(
        '${iconsDir.path}/file-peek.png',
      );

      final iconInstalled = await _installAssetIcon(
        iconFile,
      );

      final executable = Platform.resolvedExecutable;

      final desktopFile = File(
        '${applicationsDir.path}/file-peek.desktop',
      );

      final buffer = StringBuffer();

      buffer.writeln('[Desktop Entry]');
      buffer.writeln('Version=1.0');
      buffer.writeln('Type=Application');
      buffer.writeln('Name=$_appName');
      buffer.writeln('Comment=$_comment');
      buffer.writeln('Exec="${_escapeDesktopValue(executable)}"');
      buffer.writeln('Terminal=false');
      buffer.writeln('StartupNotify=true');
      buffer.writeln(
        'Categories=Utility;Development;FileManager;',
      );

      if (iconInstalled) {
        buffer.writeln('Icon=file-peek');
      }

      await desktopFile.writeAsString(
        buffer.toString(),
        flush: true,
      );

      await Process.run(
        'chmod',
        [
          '+x',
          desktopFile.path,
        ],
      );

      // Refresh the desktop database if available.
      try {
        await Process.run(
          'update-desktop-database',
          [
            applicationsDir.path,
          ],
        );
      } catch (_) {
        // Not all Linux systems have this command.
      }

      return desktopFile.existsSync();
    } catch (_) {
      return false;
    }
  }

  // ---------------------------------------------------------------------------
  // WINDOWS
  // ---------------------------------------------------------------------------

  Future<bool> _createWindowsShortcut() async {
    final appData = Platform.environment['APPDATA'];
    final userProfile = Platform.environment['USERPROFILE'];

    if (appData == null ||
        appData.isEmpty ||
        userProfile == null ||
        userProfile.isEmpty) {
      return false;
    }

    try {
      final executable = Platform.resolvedExecutable;

      final startMenuDir = Directory(
        '$appData\\Microsoft\\Windows\\Start Menu\\Programs',
      );

      final desktopDir = Directory(
        '$userProfile\\Desktop',
      );

      await startMenuDir.create(recursive: true);
      await desktopDir.create(recursive: true);

      final startMenuShortcut =
          '${startMenuDir.path}\\File Peek.lnk';

      final desktopShortcut =
          '${desktopDir.path}\\File Peek.lnk';

      /*
       * Windows shortcuts normally expect an ICO/EXE/DLL for their icon.
       *
       * We therefore use the executable itself as the primary icon source.
       * This is the safest fallback because Flutter's Windows executable
       * can contain the application icon generated by flutter_launcher_icons.
       *
       * If the executable has no usable icon, Windows will still create
       * and launch the shortcut normally.
       */

      final script = '''
\$shell = New-Object -ComObject WScript.Shell

\$target = "$executable"
\$workingDirectory = Split-Path -Parent "\$target"

\$shortcut = \$shell.CreateShortcut("$startMenuShortcut")
\$shortcut.TargetPath = \$target
\$shortcut.WorkingDirectory = \$workingDirectory
\$shortcut.Description = "$_comment"
\$shortcut.IconLocation = "\$target,0"
\$shortcut.Save()

\$shortcut = \$shell.CreateShortcut("$desktopShortcut")
\$shortcut.TargetPath = \$target
\$shortcut.WorkingDirectory = \$workingDirectory
\$shortcut.Description = "$_comment"
\$shortcut.IconLocation = "\$target,0"
\$shortcut.Save()
''';

      final result = await Process.run(
        'powershell',
        [
          '-NoProfile',
          '-NonInteractive',
          '-ExecutionPolicy',
          'Bypass',
          '-Command',
          script,
        ],
        runInShell: true,
      );

      if (result.exitCode != 0) {
        return false;
      }

      return File(startMenuShortcut).existsSync() &&
          File(desktopShortcut).existsSync();
    } catch (_) {
      return false;
    }
  }

  // ---------------------------------------------------------------------------
  // MACOS
  // ---------------------------------------------------------------------------

  Future<bool> _createMacOSApplication() async {
    final home = Platform.environment['HOME'];

    if (home == null || home.isEmpty) {
      return false;
    }

    try {
      final executable = Platform.resolvedExecutable;

      final applicationsDir = Directory(
        '$home/Applications',
      );

      await applicationsDir.create(
        recursive: true,
      );

      final appDir = Directory(
        '${applicationsDir.path}/File Peek.app',
      );

      final contentsDir = Directory(
        '${appDir.path}/Contents',
      );

      final macOSDir = Directory(
        '${contentsDir.path}/MacOS',
      );

      final resourcesDir = Directory(
        '${contentsDir.path}/Resources',
      );

      await macOSDir.create(
        recursive: true,
      );

      await resourcesDir.create(
        recursive: true,
      );

      // -----------------------------------------------------------------------
      // Copy the executable into the portable .app bundle.
      // -----------------------------------------------------------------------

      final appExecutable = File(
        '${macOSDir.path}/File Peek',
      );

      await File(executable).copy(
        appExecutable.path,
      );

      // -----------------------------------------------------------------------
      // Install the PNG as a fallback resource.
      // -----------------------------------------------------------------------

      final pngIcon = File(
        '${resourcesDir.path}/file-peek.png',
      );

      await _installAssetIcon(
        pngIcon,
      );

      // -----------------------------------------------------------------------
      // Attempt to create a proper ICNS icon from the PNG.
      //
      // If macOS does not have the required tools or conversion fails,
      // the .app is still created and remains completely functional.
      // -----------------------------------------------------------------------

      final iconSetDir = Directory(
        '${resourcesDir.path}/file-peek.iconset',
      );

      final icnsFile = File(
        '${resourcesDir.path}/file-peek.icns',
      );

      var icnsCreated = false;

      try {
        await iconSetDir.create(
          recursive: true,
        );

        final sizes = <int>[
          16,
          32,
          64,
          128,
          256,
          512,
        ];

        for (final size in sizes) {
          final output = File(
            '${iconSetDir.path}/icon_${size}x$size.png',
          );

          await Process.run(
            'sips',
            [
              '-z',
              '$size',
              '$size',
              pngIcon.path,
              '--out',
              output.path,
            ],
          );

          if (size <= 256) {
            final retinaSize = size * 2;

            final retinaOutput = File(
              '${iconSetDir.path}/icon_${size}x${size}@2x.png',
            );

            await Process.run(
              'sips',
              [
                '-z',
                '$retinaSize',
                '$retinaSize',
                pngIcon.path,
                '--out',
                retinaOutput.path,
              ],
            );
          }
        }

        final result = await Process.run(
          'iconutil',
          [
            '-c',
            'icns',
            iconSetDir.path,
            '-o',
            icnsFile.path,
          ],
        );

        if (result.exitCode == 0 &&
            icnsFile.existsSync()) {
          icnsCreated = true;
        }
      } catch (_) {
        icnsCreated = false;
      }

      // Clean up temporary iconset.
      try {
        if (iconSetDir.existsSync()) {
          await iconSetDir.delete(
            recursive: true,
          );
        }
      } catch (_) {}

      // -----------------------------------------------------------------------
      // Info.plist
      // -----------------------------------------------------------------------

      final infoPlist = File(
        '${contentsDir.path}/Info.plist',
      );

      final plist = StringBuffer();

      plist.writeln('<?xml version="1.0" encoding="UTF-8"?>');
      plist.writeln(
        '<!DOCTYPE plist PUBLIC '
        '"-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
      );
      plist.writeln('<plist version="1.0">');
      plist.writeln('<dict>');

      plist.writeln(
        '    <key>CFBundleDisplayName</key>',
      );
      plist.writeln(
        '    <string>$_appName</string>',
      );

      plist.writeln(
        '    <key>CFBundleExecutable</key>',
      );
      plist.writeln(
        '    <string>File Peek</string>',
      );

      plist.writeln(
        '    <key>CFBundleIdentifier</key>',
      );
      plist.writeln(
        '    <string>com.filepeek.app</string>',
      );

      plist.writeln(
        '    <key>CFBundleName</key>',
      );
      plist.writeln(
        '    <string>$_appName</string>',
      );

      plist.writeln(
        '    <key>CFBundlePackageType</key>',
      );
      plist.writeln(
        '    <string>APPL</string>',
      );

      plist.writeln(
        '    <key>CFBundleVersion</key>',
      );
      plist.writeln(
        '    <string>1.0.0</string>',
      );

      plist.writeln(
        '    <key>CFBundleShortVersionString</key>',
      );
      plist.writeln(
        '    <string>1.0.0</string>',
      );

      if (icnsCreated) {
        plist.writeln(
          '    <key>CFBundleIconFile</key>',
        );
        plist.writeln(
          '    <string>file-peek</string>',
        );
      }

      plist.writeln('</dict>');
      plist.writeln('</plist>');

      await infoPlist.writeAsString(
        plist.toString(),
        flush: true,
      );

      await Process.run(
        'chmod',
        [
          '+x',
          appExecutable.path,
        ],
      );

      // Tell LaunchServices about the newly-created app.
      try {
        await Process.run(
          'open',
          [
            '-a',
            appDir.path,
          ],
        );
      } catch (_) {}

      return appDir.existsSync() &&
          appExecutable.existsSync() &&
          infoPlist.existsSync();
    } catch (_) {
      return false;
    }
  }

  // ---------------------------------------------------------------------------
  // SHARED ICON INSTALLATION
  // ---------------------------------------------------------------------------

  Future<bool> _installAssetIcon(
    File destination,
  ) async {
    try {
      final byteData = await rootBundle.load(
        _assetIconPath,
      );

      final bytes = byteData.buffer.asUint8List(
        byteData.offsetInBytes,
        byteData.lengthInBytes,
      );

      await destination.writeAsBytes(
        bytes,
        flush: true,
      );

      return destination.existsSync();
    } catch (_) {
      return false;
    }
  }

  // ---------------------------------------------------------------------------
  // DESKTOP FILE ESCAPING
  // ---------------------------------------------------------------------------

  String _escapeDesktopValue(
    String value,
  ) {
    return value
        .replaceAll('\\', '\\\\')
        .replaceAll('"', '\\"');
  }
}